#!/usr/bin/env bash

do_prompt=false
verbose=false
dry_run=false

cleanup() {
	[ -n "$tmpfile" ] && rm "$tmpfile"
}

trap cleanup EXIT

invalid_tmpfile() {
	>&2 echo "Error: invalid tmpfile"
	exit 1
}

prompt() {
	local input

	[ $do_prompt = false ] && return 0

	while true; do
		read -p "$* [y/n]? " input
		case "$input" in
			[Yy]*) return 0 ;;
			[Nn]*) return 1 ;;
		esac
	done
}

verbose_msg() {
	[ "$verbose" = true ] && echo "$@"
}

for arg in "$@"; do
	case "$arg" in
		'--merged') 	;&
		'--no-merged') 	;&
		'-a') 		;&
		'--all')	;&
		'-r')		;&
		'--remotes')
			git_branch_args=(${git_branch_args[@]} "$arg")
			;;

		'-p')		;&
		'--prompt')
			do_prompt=true
			;;

		'-v')		;&
		'--verbose')
			verbose=true
			;;

		'-d')		;&
		'--dry-run')
			dry_run=true
			;;

		*)
			>&2 echo "Error: Invalid argument '$arg'"
			exit 1
			;;
	esac
done

[ $do_prompt = true ] && verbose=false

branches=($(git branch ${git_branch_args[@]} | sed 's/\*//g'))
tmpfile=$(mktemp)
index=1

for branch in "${branches[@]}"; do
	printf "%04d\t%s\n" "$index" "$branch" >> "$tmpfile"
	let index++
done

"${EDITOR:-vi}" "$tmpfile"

deleted=${branches[@]}

while read -u 200 line; do
	read -ra components <<<"$line"

	[ ${#components[@]} -ne 2 ] && invalid_tmpfile

	let index=components[0]-1
	let name=components[1]
	let original=branches[index]

	deleted=("${deleted/$original}")

	if [ "$original" != "$name" ] && prompt "Rename $original to $name"; then
		verbose_msg "Renaming $original to $name"
		[ "$dry_run" = false ] && git branch "$original" -m "$name"
	fi
done 200< "$tmpfile"

for branch in ${deleted[@]}; do
	if prompt "Delete branch $branch"; then
		verbose_msg "Deleting branch $branch"
		[ "$dry_run" = false ] && git branch -D "$branch"
	fi
done
