#!/usr/bin/env bash
set -e
rev=$(git log --color --oneline "$@" | fzf --ansi | cut -f1 -d' ')

if [ -z $rev ]; then
  exit 1
fi

if [ ! -t 1 ]; then
  echo "$rev"
  exit
fi

git update-ref refs/PICK "$rev"
