#!/usr/bin/env bash
set -e

line=$(git log --color --oneline "$@" | fzf --ansi --preview 'git show --color {1}')

[ -z $line ] && exit 1

rev=${line%%\ *}

if [ ! -t 1 ]; then
  echo "$rev"
  exit
fi

git update-ref refs/PICK "$rev"
