#!/usr/bin/env bash

declare -A files

their_msg="$(git log -1 --format=%s HEAD)"
our_msg="$(git log -1 --format=%s MERGE_HEAD)"

while read -r file; do
	files["$file"]=
done < <(git diff --name-only --diff-filter=M)

yellow() {
	echo $'\x1b[33m'"$*"$'\x1b[0m'
}

blue() {
	echo $'\x1b[34m'"$*"$'\x1b[0m'
}

bold() {
	echo $'\x1b[1m'"$*"$'\x1b[0m'
}

faint() {
	echo $'\x1b[2m'"$*"$'\x1b[0m'
}

prompt_file() {
	local file
	file="$1"

	[ ! -e "$file" ] && return

	local content
	mapfile -t content <"$file"

	offset=0

	local lineno start end mid
	lineno=0
	start=0
	end=0
	mid=0

	bold "Resolving file $file"

	local line
	while read -r line; do
		((lineno++)) || :

		case "$line" in
		'<<<<<<<'*)
			start="$lineno"
			echo "$(yellow "$line") $(faint "$their_msg")"
			;;
		'======='*)
			mid="$lineno"
			yellow "$line"
			;;
		'>>>>>>>'*)
			end="$lineno"
			echo "$(yellow "$line") $(faint "$our_msg")"
			prompt_conflict "$file" "$start" "$mid" "$end" </dev/tty || return
			;;
		*)
			[ "$start" -gt "$end" ] && echo "$line"
			;;
		esac
	done <"$(printf "%s\n" "${content[@]}")"

	git add "$file"
}

prompt_conflict() {
	local file start end mid

	file="$1"
	start="$2"
	mid="$3"
	end="$4"

	((start+=offset))
	((mid+=offset))
	((end+=offset))

	local reply
	while read -r -p "$(blue "Keep (t)op/(b)ottom, (e)dit, (s)kip conflict, skip (f)ile, (a)bort or (q)uit [t/b/e/s/f/a/q]? ")" reply; do
		case "$reply" in
		[tT]*)
			sed -i "${mid},${end}d; ${start}d" "$file"
			((offset-=end-mid+2))
			;;
		[bB]*)
			sed -i "${start},${mid}d; ${end}d" "$file"
			((offset-=mid-start+2))
			;;
		[eE]*)
			local before after _
			read -r before _ < <(wc -l "$file")
			"${EDITOR:-vi}" "$file" +"$start"
			read -r after _ < <(wc -l "$file")
			((offset-=before-after))
			;;
		[sS]*) return 0 ;;
		[fF]*)
			git add "$file"
			return 1
			;;
		[qQ]*)
			git add "$file"
			exit
			;;
		[aA]*) exit ;;
		*) continue ;;
		esac
		break
	done
}

for file in "${!files[@]}"; do
	prompt_file "$file"
	echo
done
